version: "3.7"

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  zk_log: {}
  zk_data: {}
  kafka0_data: {}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    networks:
      kafka:
        aliases:
          - postgres

  # Need 3.5 or later for container nodes
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    expose:
      - 2181
      - 2888
      - 3888
    networks:
      kafka:
        aliases:
          - zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOO_MY_ID=1
    volumes:
    - zk_data:/var/lib/zookeeper/data
    - zk_log:/var/lib/zookeeper/log


  #https://docs.confluent.io/current/kafka/multi-node.html
  kafka-0:
    container_name: kafka-0
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=LISTENER_INTERNAL://kafka-0:19092,LISTENER_PUBLIC://kafka-0:9092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-0:19092,LISTENER_PUBLIC://kafka-0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_PUBLIC:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL

    volumes:
    - kafka0_data:/var/lib/kafka/data
    - ./kafka-0.properties:/etc/kafka/server.properties
    networks:
      kafka:
        aliases:
          - kafka-0
    depends_on:
      - zookeeper

  coordinator:
    image: apache/druid:0.21.1-rc1
    container_name: coordinator
    volumes:
      - ./storage:/opt/data
      - coordinator_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment
    networks:
      kafka:
        aliases:
          - coordinator
  broker:
    image: apache/druid:0.21.1-rc1
    container_name: broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment
    networks:
      kafka:
        aliases:
          - broker

  historical:
    image: apache/druid:0.21.1-rc1
    container_name: historical
    volumes:
      - ./storage:/opt/data
      - historical_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment
    networks:
      kafka:
        aliases:
          - historical
  middlemanager:
    image: apache/druid:0.21.1-rc1
    container_name: middlemanager
    volumes:
      - ./storage:/opt/data
      - middle_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
    command:
      - middleManager
    env_file:
      - environment
    networks: 
      kafka:
        aliases:
          - middlemanager
  router:
    image: apache/druid:0.21.1-rc1
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment
    networks: 
      kafka:
        aliases:
          - router
networks:
  kafka: {}      
      
      
      